from abc import ABC, abstractmethod

import numpy as np
import pandas as pd
from IPython.core.getipython import get_ipython
from ..utils import *

class Drag(ABC):
    def  __init__(self, config):
        self.config = config

    def data(self, file_path, df_name='df'):
        self.add_cell(f"# Code generated by DRAG\nimport numpy as np\nimport pandas as pd\n\n{df_name} = pd.read_csv('{file_path}')")
        self.add_questions(question=df_name, output=str(pd.read_csv(file_path).head(3)))

    def ask(self, data: dict, question: str):
        llm_response = self.generate_prompt(data=data, question=question)
        self.add_questions(question=question, output=llm_response)
        self.add_cell(f"# Code generated by DRAG\n{llm_response}")

    def add_cell(self, text, source='set_next_input', replace=False):
        shell = get_ipython()
        payload = dict(
            source=source,
            text=text,
            replace=replace,
        )
        shell.payload_manager.write_payload(payload, single=False)

    def generate_prompt(self, data, question: str, question_enhancer=False, **kwargs) -> str:
            #question_sql_list = self.get_similar_question_sql(question, **kwargs)
            if question_enhancer:
                question = self.question_enhancer(question, data)
            prompt = self.get_prompt(
                data=data,
                question=question,
                **kwargs,
            )
            llm_response = self.submit_prompt(prompt, **kwargs)
            clean_response = self.clear_llm_response(llm_response)
            return clean_response

    def get_prompt( self, data: dict, question: str, **kwargs,):
            data_keys = [k for k in data.keys()]
            data_values = [v for v in data.values()]
            initial_prompt = f"The user poses a query and you provide the python code. \
You answer only with python code and not with explanations. \
You do not respond with explanations, but only with code.\n\
The code you generate will be inserted inside a Python notebook, \
in which a Pandas DataFrame called {', '.join(data_keys)} has already been declared.\n\n\
Consider the following DataFrame {', '.join(data_keys)}:\n"
            initial_prompt = self.add_df_to_prompt(initial_prompt=initial_prompt, data=data_values)
            initial_prompt  += f"\nGenerates python code that enables:\n{question}"
            return initial_prompt

    def add_df_to_prompt(self, initial_prompt: str, data) -> str:
            for d in data:
                if len(d) > 4:
                    initial_prompt += f"{str(d.head(3))}\n"
                else:
                    initial_prompt += f"{str(d)}\n"
            return initial_prompt
    
    def question_enhancer(self, question, data):
        data_keys = [k for k in data.keys()]
        data_values = [v for v in data.values()]
        initial_prompt = f"The following sentence will be used in a prompt:\n{question}\n\n\
Enhance the sentence considering that it refers to the following DataFrames {', '.join(data_keys)}:\n"
        initial_prompt = self.add_df_to_prompt(initial_prompt=initial_prompt, data=data_values)
        initial_prompt  += f"\nEnhance the sentence so that the LLM receiving the prompt will be facilitated in carrying out its task.\n\
Return only the improved sentence, it is very important that you do not return anything else."
        return self.submit_prompt(initial_prompt, temperature=0.1)